TravelBug/Controllers/Pages/AdminController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TravelBug.Controllers.Pages
{
    using Components;
    using Models.Model;
    using Models.TravelBugModel;
    using Excursion = Models.TravelBugModel.Excursion;
    using Language = Models.TravelBugModel.Language;
    using Photo = Models.TravelBugModel.Photo;

    public class AdminController : BaseController
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public JsonResult OnCreate()
        {
            var excursion = manager.GetExcursionByID(
                manager.CreateExcursion(new Models.TravelBugModel.Excursion())
                );

            var result = new
            {
                Id = excursion.Id
                //,
                //Title = excursion.Title,
                //Description = excursion.Description,
                //TimeID = excursion.TimeID
            };

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="newExcursion"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult OnUpdate(Excursion newExcursion)
        {
            var result = manager.CreateOrUpdateExcursion(newExcursion);

            return Json(true, JsonRequestBehavior.AllowGet);
        }
        
        [HttpPost]
        public ActionResult UploadFiles(int id)
        {
            // Checking no of files injected in Request object  
            if (Request.Files.Count > 0)
            {
                try
                {
                    //  Get all files from Request object  
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {
                        //string path = AppDomain.CurrentDomain.BaseDirectory + "Uploads/";  
                        //string filename = Path.GetFileName(Request.Files[i].FileName);  

                        HttpPostedFileBase file = files[i];
                        string fname;

                        // Checking for Internet Explorer  
                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {
                            string[] testfiles = file.FileName.Split(new char[] { '\\' });
                            fname = testfiles[testfiles.Length - 1];
                        }
                        else
                        {
                            fname = file.FileName;
                        }

                        Photo photo = new Photo();
                        photo.FileName = fname;
                        photo.ContentType = file.ContentType;
                        photo.ExcursionID = id;

                        using (var reader = new System.IO.BinaryReader(file.InputStream))
                        {
                            //picture.Picture = reader.ReadBytes(file.ContentLength);
                            photo.Image = CompressionImage.GetCroppedImage(reader.ReadBytes(file.ContentLength),
                                CompressionImage.GetFormatImage(file.ContentType));
                        }

                        manager.CreatePhoto(photo);
                    }
                    return Json(true);
                }
                catch (Exception ex)
                {
                    return Json("Error occurred. Error details: " + ex.Message);
                }
            }
            else
            {
                return Json("No files selected.");
            }
        }


        /// <summary>
        /// Получения данных для карточки
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult OnEdit(int id)
        {
            var excursion = manager.GetExcursionByID(id);

            if (excursion.Cost != null && excursion.Cost.Count() == 1)
            {
                excursion.Cost.ElementAt(0).Excursion = null;
            }

            Excursion exc = GetExcursionWithoutEndlessCycle(excursion);

            //Что бы не было цикличной сериализации
            JsonSerializerSettings settings =
                new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };

            var tmp = JsonConvert.SerializeObject(exc, settings);
            return Json(tmp, JsonRequestBehavior.AllowGet);
        }

        #region Remove elements

        [HttpPost]
        public JsonResult OnRemoveTour(int id)
        {
            var result = manager.DeleteExcursionByID(id);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult OnRemoveImages(int id, RemoveFiles[] removeFiles)
        {
            if (removeFiles != null)
            {
                for (int i = 0; i < removeFiles.Length; i++)
                {
                    if (id == removeFiles[i].ExcursionID)
                    {
                        if (removeFiles[i].Delete)
                            manager.RemovePhotoByID(removeFiles[i].ID);
                        else
                            manager.UpdatePhotoByID(removeFiles[i].ID, removeFiles[i].Hide);
                    }
                }
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Get collection

        [HttpGet]
        public JsonResult GetDataForTable()
        {
            var data = manager.GetExcursions();

            var result = (from m in data
                          where m.Id != 0
                          select new
                          {
                              id = m.Id,
                              Title = m.Title,
                              Description = m.Description,
                              Time = m.TimeID
                          });



            return Json(result.ToArray(), JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetTimes()
        {
            var times = manager.GetTime().ToArray();

            var jsonTimes = JsonConvert.SerializeObject(times);

            return Json(jsonTimes, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult GetMoney()
        {
            var arr = manager.GetCost().ToArray();
            List<Cost> costs = arr.GroupBy(car => car.Money).Select(g => g.First()).ToList();

            List<Cost> money = new List<Cost>();

            for (int i = 0; i < costs.Count(); i++)
            {
                Cost cost = new Cost
                {
                    ID = costs[i].ID,
                    ExcursionID = costs[i].ExcursionID,
                    Money = costs[i].Money
                };
                money.Add(cost);
            }

            //Что бы не было цикличной сериализации
            JsonSerializerSettings settings =
                new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };

            var tmp = JsonConvert.SerializeObject(money, settings);

            return Json(tmp, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult getFiles(int id)
        {
            var files = manager.GetPhotoByExcursionID(id).ToArray();

            List<Photo> photos = new List<Photo>();
            for (int i = 0; i < files.Length; i++)
            {
                Photo photo = new Photo
                {
                    ContentType = files[i].ContentType,
                    ID = files[i].ID,
                    Image = files[i].Image,
                    FileName = files[i].FileName,
                    Delete = files[i].Delete
                };
                photos.Add(photo);
            }

            //Что бы не было цикличной сериализации
            JsonSerializerSettings settings =
                new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };

            var tmp = JsonConvert.SerializeObject(photos, settings);

            return Json(tmp, JsonRequestBehavior.AllowGet);
        }

        #endregion
    }
}

TravelBug/Controllers/Pages/ExcursionController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelBug.Models.TravelBugModel;

namespace TravelBug.Controllers.Pages
{
    public class ExcursionController : BaseController
    {
        [HttpGet]
        public ActionResult View(int id)
        {
            ViewBag.ExcursionID = id;
            return View();
        }

        [HttpGet]
        public JsonResult GetTourByID(int id)
        {
            var excursion = manager.GetExcursionByID(id);

            Time time = excursion.TimeID != null ? manager.GetTimeByID(excursion.TimeID ?? 0) : null;

            var exc = new
            {
                Id = excursion.Id,
                Title = excursion.Title,
                Description = excursion.Description,
                Time = time,
                Language = excursion.Language.Where(x => x.ID != 0)
                .Select(x =>
                new Language
                {
                    ID = x.ID,
                    Name_Language = x.Name_Language,
                    ExcursionID = x.ExcursionID
                }).ToArray(),
                Photo = excursion.Photo.Where(x => x.Delete != true).Select(x =>
               new Photo
               {
                   ID = x.ID,
                   ExcursionID = x.ExcursionID,
                   FileName = x.FileName,
                   ContentType = x.ContentType,
                   ToMine = x.ToMine,
                   Image = x.Image,
                   Delete = false // Тут delete играет роль "отображение на стороне клиента эту картинку или нет "
               }).ToArray(),
                Cost = new Cost { Money = excursion.Cost.FirstOrDefault().Money }
            };

            if (exc != null && exc.Photo != null) // && exc.Photo.Count != 0)
            {
                var tmpPhoto = exc.Photo.FirstOrDefault();
                if (tmpPhoto != null)
                {
                    tmpPhoto.Delete = true;
                }
            }


            JsonSerializerSettings settings =
              new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };

            var tmp = JsonConvert.SerializeObject(exc, settings);

            return Json(tmp, JsonRequestBehavior.AllowGet);
        }
    }
}

TravelBug/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html ng-app="TravelBagApp" lang="en">
<head>
    <meta charset="UTF-8">
    <title>TravelBug</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />

    <!--[if lte IE 8]><script src="js/html5shiv.js"></script><![endif]-->
    <script src="~/Content/Scripts/js/jquery.min.js"></script>
    @*<script src="~/Scripts/jquery-3.1.1.min.js"></script>*@
    <script src="~/Content/Scripts/js/new_skel.min.js"></script>
    <script src="~/Content/Scripts/js/skel-layers.min.js"></script>
    <script src="~/Content/Scripts/js/init.js"></script>
    <noscript>
        <link rel="stylesheet" href="~/Content/Style/css/skel.css" />
        <link rel="stylesheet" href="~/Content/Style/css/style.css" />
        <link rel="stylesheet" href="~/Content/Style/css/style-xlarge.css" />
    </noscript>


    <link rel="import" href="~/TravelBug.UI/BaseFileStyle.html">
    <link rel="import" href="~/TravelBug.UI/BaseFileScript.html">

    <script>
        (function () {
            var version = "1.2.2.0";
            'use strict';
            var app = angular.module("TravelBagApp",
                  [
                      "ngMessages",
                      "ngSanitize",
                      "ngRoute",
                      "ngMaterial",
                      ////"ngFileUpload",
                      ////"kendo.directives",
                      ////'vAccordion',
                      'ngAnimate',
                      'ngMaterial',
                      "TravelBagApp.Common",
                      "TravelBagApp.Services",
                      "TravelBagApp.Controllers"
                  ]);
            angular.module("TravelBagApp.Common", []); //ToDo ??
            angular.module("TravelBagApp.Services", []);
            angular.module("TravelBagApp.Controllers", []);
            //app
            //    //Для таблицы в админке
            //    .config(['$mdThemingProvider', function ($mdThemingProvider) {
            //        'use strict';

            //        $mdThemingProvider.theme('default')
            //          .primaryPalette('blue')
            //          .accentPalette('pink');
            //    }]);
        })();
    </script>
</head>
<body class="landing">
    <!-- Header -->
    <header id="header">
        <h1>@Html.ActionLink("TravelBug", "MainView", "Home")</h1>
        <nav id="nav">
            <ul>
                <li><a href="index.html">Home</a></li>
                <li><a href="generic.html">Generic</a></li>
                <li><a href="elements.html">Elements</a></li>
                <li><a href="#" class="button special">Sign Up</a></li>
                <li>@Html.ActionLink("Create new Excursion", "Excursion", "Create")</li>
                <li>@Html.ActionLink("get all Excursion", "Index", "Admin")</li>
                <li>@Html.ActionLink("Home page", "MainView", "Home")</li>
            </ul>
        </nav>
    </header>

    <!-- Banner -->
    <section id="banner">
        <h2>Hi. This is TravelBug.</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        <ul class="actions">
            <li>
                <a href="#" class="button big">Lorem ipsum dolor</a>
            </li>
        </ul>
    </section>

    <!-- One -->
    @RenderBody()
    <!-- Two -->
    <section id="two" class="wrapper style2 special"></section>
    <!-- Footer -->
    <footer id="footer">
        <div class="container">
            <section class="links">
                <div class="row">
                    <section class="3u 6u(medium) 12u$(small)">
                        <h3>Lorem ipsum dolor</h3>
                        <ul class="unstyled">
                            <li><a href="#">Lorem ipsum dolor sit</a></li>
                            <li><a href="#">Nesciunt itaque, alias possimus</a></li>
                            <li><a href="#">Optio rerum beatae autem</a></li>
                            <li><a href="#">Nostrum nemo dolorum facilis</a></li>
                            <li><a href="#">Quo fugit dolor totam</a></li>
                        </ul>
                    </section>
                    <section class="3u 6u$(medium) 12u$(small)">
                        <h3>Culpa quia, nesciunt</h3>
                        <ul class="unstyled">
                            <li><a href="#">Lorem ipsum dolor sit</a></li>
                            <li><a href="#">Reiciendis dicta laboriosam enim</a></li>
                            <li><a href="#">Corporis, non aut rerum</a></li>
                            <li><a href="#">Laboriosam nulla voluptas, harum</a></li>
                            <li><a href="#">Facere eligendi, inventore dolor</a></li>
                        </ul>
                    </section>
                    @*<section class="3u 6u(medium) 12u$(small)">
                        <h3>Neque, dolore, facere</h3>
                        <ul class="unstyled">
                            <li><a href="#">Lorem ipsum dolor sit</a></li>
                            <li><a href="#">Distinctio, inventore quidem nesciunt</a></li>
                            <li><a href="#">Explicabo inventore itaque autem</a></li>
                            <li><a href="#">Aperiam harum, sint quibusdam</a></li>
                            <li><a href="#">Labore excepturi assumenda</a></li>
                        </ul>
                    </section>
                    <section class="3u$ 6u$(medium) 12u$(small)">
                        <h3>Illum, tempori, saepe</h3>
                        <ul class="unstyled">
                            <li><a href="#">Lorem ipsum dolor sit</a></li>
                            <li><a href="#">Recusandae, culpa necessita nam</a></li>
                            <li><a href="#">Cupiditate, debitis adipisci blandi</a></li>
                            <li><a href="#">Tempore nam, enim quia</a></li>
                            <li><a href="#">Explicabo molestiae dolor labore</a></li>
                        </ul>
                    </section>*@
                </div>
            </section>
            <div class="row">
                <div class="8u 12u$(medium)">
                    <ul class="copyright">
                        <li>&copy; Untitled. All rights reserved.</li>
                        <li>Design: <a href="http://templated.co">TEMPLATED</a></li>
                        <li>Images: <a href="http://unsplash.com">Unsplash</a></li>
                    </ul>
                </div>
                <div class="4u$ 12u$(medium)">
                    <ul class="icons">
                        <li>
                            <a class="icon rounded fa-facebook"><span class="label">Facebook</span></a>
                        </li>
                        <li>
                            <a class="icon rounded fa-twitter"><span class="label">Twitter</span></a>
                        </li>
                        <li>
                            <a class="icon rounded fa-google-plus"><span class="label">Google+</span></a>
                        </li>
                        <li>
                            <a class="icon rounded fa-linkedin"><span class="label">LinkedIn</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    @*<script src="~/Content/Scripts/bootstrap.min.js"></script>*@
</body>
</html>

TravelBug/Views/Shared/_LayoutMin.cshtml
<!DOCTYPE html>
<html ng-app="TravelBagApp" lang="en">
@*ng-app="TravelBagApp">*@
<head>
    <meta charset="UTF-8">
    <title>@ViewBag.Title</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <!--[if lte IE 8]><script src="js/html5shiv.js"></script><![endif]-->
    <script src="~/Content/Scripts/js/jquery.min.js"></script>
    @*<script src="~/Scripts/jquery-3.1.1.min.js"></script>*@
    <script src="~/Content/Scripts/js/new_skel.min.js"></script>
    <script src="~/Content/Scripts/js/skel-layers.min.js"></script>
    <script src="~/Content/Scripts/js/init.js"></script>
    <noscript>
        <link rel="stylesheet" href="~/Content/Style/css/skel.css" />
        <link rel="stylesheet" href="~/Content/Style/css/style.css" />
        <link rel="stylesheet" href="~/Content/Style/css/style-xlarge.css" />
    </noscript>


    <link rel="import" href="~/TravelBug.UI/BaseFileStyle.html">
    <link rel="import" href="~/TravelBug.UI/BaseFileScript.html">

    <script>
        (function () {
            var version = "1.2.2.0";
            'use strict';
            var app = angular.module("TravelBagApp",
                  [
                      "ngMessages",
                      "ngSanitize",
                      "ngRoute",
                      "ngMaterial",
                      ////"ngFileUpload",
                      ////"kendo.directives",
                      ////'vAccordion',
                      'ngAnimate',
                      'ngMaterial',
                      "TravelBagApp.Common",
                      "TravelBagApp.Services",
                      "TravelBagApp.Controllers"
                  ]);
            angular.module("TravelBagApp.Common", []); //ToDo ??
            angular.module("TravelBagApp.Services", []);
            angular.module("TravelBagApp.Controllers", []);
            //app
            //    //Для таблицы в админке
            //    .config(['$mdThemingProvider', function ($mdThemingProvider) {
            //        'use strict';

            //        $mdThemingProvider.theme('default')
            //          .primaryPalette('blue')
            //          .accentPalette('pink');
            //    }]);
        })();
    </script>
</head>
<body>
    <!-- Header -->
    <header id="header">
        <h1>@Html.ActionLink("TravelBug", "Home", "Home")</h1>
        <nav id="nav">
            <ul>
                <li><a href="#" class="button special">Sign Up</a></li>
                <li>@Html.ActionLink("get all Excursion", "Index", "Admin")</li>
                <li>@Html.ActionLink("Home page", "Home", "Home")</li>
            </ul>
        </nav>
    </header>

    @RenderBody()

    <!-- Footer -->
    <footer id="footer">
        <div class="container">
            <section class="links">
                <div class="row">
                    <section class="3u 6u(medium) 12u$(small)">
                        <h3>Lorem ipsum dolor</h3>
                        <ul class="unstyled">
                            <li><a href="#">Lorem ipsum dolor sit</a></li>
                            <li><a href="#">Nesciunt itaque, alias possimus</a></li>
                            <li><a href="#">Optio rerum beatae autem</a></li>
                            <li><a href="#">Nostrum nemo dolorum facilis</a></li>
                            <li><a href="#">Quo fugit dolor totam</a></li>
                        </ul>
                    </section>
                    <section class="3u 6u$(medium) 12u$(small)">
                        <h3>Culpa quia, nesciunt</h3>
                        <ul class="unstyled">
                            <li><a href="#">Lorem ipsum dolor sit</a></li>
                            <li><a href="#">Reiciendis dicta laboriosam enim</a></li>
                            <li><a href="#">Corporis, non aut rerum</a></li>
                            <li><a href="#">Laboriosam nulla voluptas, harum</a></li>
                            <li><a href="#">Facere eligendi, inventore dolor</a></li>
                        </ul>
                    </section>
                </div>
            </section>
            <div class="row">
                <div class="8u 12u$(medium)">
                    <ul class="copyright">
                        <li>&copy; Untitled. All rights reserved.</li>
                        <li>Design: <a href="http://templated.co">TEMPLATED</a></li>
                        <li>Images: <a href="http://unsplash.com">Unsplash</a></li>
                    </ul>
                </div>
                <div class="4u$ 12u$(medium)">
                    <ul class="icons">
                        <li>
                            <a class="icon rounded fa-facebook"><span class="label">Facebook</span></a>
                        </li>
                        <li>
                            <a class="icon rounded fa-twitter"><span class="label">Twitter</span></a>
                        </li>
                        <li>
                            <a class="icon rounded fa-google-plus"><span class="label">Google+</span></a>
                        </li>
                        <li>
                            <a class="icon rounded fa-linkedin"><span class="label">LinkedIn</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    @*<link rel="import" href="~/TravelBug.UI/BaseFileScript.html">*@
</body>
</html>

TravelBug/Views/Shared/_LayoutMinAdmin.cshtml
<!DOCTYPE html>
<html ng-app="TravelBagApp" lang="en">
@*ng-app="TravelBagApp">*@
<head>
    <meta charset="UTF-8">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    @*<meta name="viewport" content="width=device-width, initial-scale=1.0">*@
    <!--[if lte IE 8]><script src="~/Content/Scripts/js/html5shiv.js"></script><![endif]-->
    <script src="~/Content/Scripts/js/jquery.min.js"></script>
    @*<script src="~/Content/Scripts/js/skel.min.js"></script>*@
    <script src="~/Content/Scripts/js/skel-layers.min.js"></script>
    <script src="~/Content/Scripts/js/init.js"></script>

    <link rel="stylesheet" href="~/Content/Style/css/skel.css" type="text/css" />
    <link rel="stylesheet" href="~/Content/Style/css/style.css" />
    <link rel="stylesheet" href="~/Content/Style/css/style-xlarge.css" />


    <link rel="import" href="~/TravelBug.UI/BaseFileStyle.html">
    <link rel="import" href="~/TravelBug.UI/BaseFileScript.html">

    <script>
        (function () {
            var version = "1.2.2.0";
            'use strict';
            var app = angular.module("TravelBagApp",
                  [
                      "ngMessages",
                      "ngSanitize",
                      "ngRoute",
                      "ngMaterial",
                      ////"ngFileUpload",
                      ////"kendo.directives",
                      ////'vAccordion',
                      'ngAnimate',
                      'md.data.table',
                      'ngMaterial',
                      "TravelBagApp.Common",
                      "TravelBagApp.Services",
                      "TravelBagApp.Controllers"
                  ]);
            angular.module("TravelBagApp.Common", []); //ToDo ??
            angular.module("TravelBagApp.Services", []);
            angular.module("TravelBagApp.Controllers", []);
            app
                //Для таблицы в админке
                .config(['$mdThemingProvider', function ($mdThemingProvider) {
                    'use strict';

                    $mdThemingProvider.theme('default')
                      .primaryPalette('blue')
                      .accentPalette('pink');
                }]);
        })();
    </script>
</head>
<body>
    <!-- Header -->
    <header id="header">
        <h1><a href="index.html">Transit</a></h1>
        <nav id="nav">
            <ul>
                <li><a href="index.html">Home</a></li>
                <li><a href="generic.html">Generic</a></li>
                <li><a href="elements.html">Elements</a></li>
                <li><a href="#" class="button special">Sign Up</a></li>
                <li>@Html.ActionLink("Admin page", "Admin", "Index")</li>
                <li>@Html.ActionLink("get all Excursion (old)", "AdminPage", "Excursions")</li>
                <li>@Html.ActionLink("Home page", "Home", "Home")</li>
            </ul>
        </nav>
    </header>

    @RenderBody()

    <!-- Footer -->
    <footer id="footer">
        <div class="container">
            <section class="links">
                <div class="row">
                    <section class="3u 6u(medium) 12u$(small)">
                        <h3>Lorem ipsum dolor</h3>
                        <ul class="unstyled">
                            <li><a href="#">Lorem ipsum dolor sit</a></li>
                            <li><a href="#">Nesciunt itaque, alias possimus</a></li>
                            <li><a href="#">Optio rerum beatae autem</a></li>
                            <li><a href="#">Nostrum nemo dolorum facilis</a></li>
                            <li><a href="#">Quo fugit dolor totam</a></li>
                        </ul>
                    </section>
                    <section class="3u 6u$(medium) 12u$(small)">
                        <h3>Culpa quia, nesciunt</h3>
                        <ul class="unstyled">
                            <li><a href="#">Lorem ipsum dolor sit</a></li>
                            <li><a href="#">Reiciendis dicta laboriosam enim</a></li>
                            <li><a href="#">Corporis, non aut rerum</a></li>
                            <li><a href="#">Laboriosam nulla voluptas, harum</a></li>
                            <li><a href="#">Facere eligendi, inventore dolor</a></li>
                        </ul>
                    </section>
                    <section class="3u 6u(medium) 12u$(small)">
                        <h3>Neque, dolore, facere</h3>
                        <ul class="unstyled">
                            <li><a href="#">Lorem ipsum dolor sit</a></li>
                            <li><a href="#">Distinctio, inventore quidem nesciunt</a></li>
                            <li><a href="#">Explicabo inventore itaque autem</a></li>
                            <li><a href="#">Aperiam harum, sint quibusdam</a></li>
                            <li><a href="#">Labore excepturi assumenda</a></li>
                        </ul>
                    </section>
                    <section class="3u$ 6u$(medium) 12u$(small)">
                        <h3>Illum, tempori, saepe</h3>
                        <ul class="unstyled">
                            <li><a href="#">Lorem ipsum dolor sit</a></li>
                            <li><a href="#">Recusandae, culpa necessita nam</a></li>
                            <li><a href="#">Cupiditate, debitis adipisci blandi</a></li>
                            <li><a href="#">Tempore nam, enim quia</a></li>
                            <li><a href="#">Explicabo molestiae dolor labore</a></li>
                        </ul>
                    </section>
                </div>
            </section>
            <div class="row">
                <div class="8u 12u$(medium)">
                    <ul class="copyright">
                        <li>&copy; Untitled. All rights reserved.</li>
                        <li>Design: <a href="http://templated.co">TEMPLATED</a></li>
                        <li>Images: <a href="http://unsplash.com">Unsplash</a></li>
                    </ul>
                </div>
                <div class="4u$ 12u$(medium)">
                    <ul class="icons">
                        <li>
                            <a class="icon rounded fa-facebook"><span class="label">Facebook</span></a>
                        </li>
                        <li>
                            <a class="icon rounded fa-twitter"><span class="label">Twitter</span></a>
                        </li>
                        <li>
                            <a class="icon rounded fa-google-plus"><span class="label">Google+</span></a>
                        </li>
                        <li>
                            <a class="icon rounded fa-linkedin"><span class="label">LinkedIn</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    @*<link rel="import" href="~/TravelBug.UI/BaseFileScript.html">*@
</body>
</html>