TravelBug/Controllers/Pages/ExcursionToServer/Step1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelBug.Controllers.Components;
using TravelBug.Models.TravelBugModel;

namespace TravelBug.Controllers.Pages.ExcursionToServer
{
    public class Step1Controller : BaseController
    {
        [HttpGet]
        public ActionResult CreateNew()
        {
            ViewBag.TimeCollection = manager.GetTime().ToList();
            return View();
        }

        [HttpPost]
        public ActionResult CreateNew(Excursion excursion, string Name_Language, string Money,
            HttpPostedFileBase[] Pictures)
        {
            var newExcursion = manager.CreateOrUpdateExcursion(excursion, Name_Language, Money);

            if (Pictures != null && Pictures.Count() > 0 && Pictures[0] != null)
            {
                PhotoBase photo = new PhotoBase();
                photo.AddPhotosByExecursionID(newExcursion.Id, Pictures);
            }

            return RedirectToAction("GetAllExcursions", "Excursion");
        }
    }
}

TravelBug/Views/Step1/CreateNew.cshtml
@model TravelBug.Models.TravelBugModel.Excursion

@{
    ViewBag.Title = "CreateNew";
}

<h2>CreateNew</h2>

@using (Html.BeginForm("CreateNew", "Step1", null, FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Excursion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        @Html.Action("Item", "DropDownListEdit", new { type = "Language", id = -1 })

        @Html.Action("Item", "DropDownListEdit", new { type = "Cost", id = -1 })

        @Html.Action("Item", "DropDownListEdit", new { type = "Time", id = -1 })

       
        <section id="AddImage">
            @Html.Partial("AddImagePartial")
        </section>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Go to create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>