TravelBug/Models/TravelBugModel/Excursion.cs
namespace TravelBug.Models.TravelBugModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Excursion")]
    public partial class Excursion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Excursion()
        {
            Cost = new HashSet<Cost>();
            Language = new HashSet<Language>();
            Photo = new HashSet<Photo>();
        }

        [Required]
        public int Id { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public bool Deleted { get; set; }

        public int? TimeID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cost> Cost { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Language> Language { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photo { get; set; }
    }
}

TravelBug/Controllers/Elements/ExcursionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace TravelBug.Controllers.Elements
{
    public class ExcursionController : BaseController
    {

        public ActionResult GetAllExcursions()
        {
            ViewBag.Excursions = manager.GetExcursion().ToList();
            return View();
        }


        /// <summary>
        /// Получаем экскурсию по айди
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult ExcursionView(int? id)
        {
            if (id == null)
            {
                return View(manager.GetExcursionByID(id ?? 0));
            }
            else
            {
                return View();
            }
        }
    }
}

TravelBug/Controllers/Pages/ExcursionController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelBug.Models.TravelBugModel;

namespace TravelBug.Controllers.Pages
{
    public class ExcursionController : BaseController
    {
        [HttpGet]
        public ActionResult View(int id)
        {
            ViewBag.ExcursionID = id;
            return View();
        }

        [HttpGet]
        public JsonResult GetTourByID(int id)
        {
            var excursion = manager.GetExcursionByID(id);

            Time time = excursion.TimeID != null ? manager.GetTimeByID(excursion.TimeID ?? 0) : null;

            var exc = new
            {
                Id = excursion.Id,
                Title = excursion.Title,
                Description = excursion.Description,
                Time = time,
                Language = excursion.Language.Where(x => x.ID != 0)
                .Select(x =>
                new Language
                {
                    ID = x.ID,
                    Name_Language = x.Name_Language,
                    ExcursionID = x.ExcursionID
                }).ToArray(),
                Photo = excursion.Photo.Where(x => x.Delete != true).Select(x =>
               new Photo
               {
                   ID = x.ID,
                   ExcursionID = x.ExcursionID,
                   FileName = x.FileName,
                   ContentType = x.ContentType,
                   ToMine = x.ToMine,
                   Image = x.Image,
                   Delete = false // Тут delete играет роль "отображение на стороне клиента эту картинку или нет "
               }).ToArray(),
                Cost = new Cost { Money = excursion.Cost.FirstOrDefault().Money }
            };

            if (exc != null && exc.Photo != null) // && exc.Photo.Count != 0)
            {
                var tmpPhoto = exc.Photo.FirstOrDefault();
                if (tmpPhoto != null)
                {
                    tmpPhoto.Delete = true;
                }
            }


            JsonSerializerSettings settings =
              new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };

            var tmp = JsonConvert.SerializeObject(exc, settings);

            return Json(tmp, JsonRequestBehavior.AllowGet);
        }
    }
}

TravelBug/Controllers/Pages/ExcursionToServer/ShowImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelBug.Models.TravelBugModel;

namespace TravelBug.Controllers
{
    public class ShowImageController : BaseController
    {
        public ActionResult GetUrlFromPictureOfExcursion(int excursionID)
        {
            Photo picture = manager.GetMainPhotoByExcursionID(excursionID);


            if (picture != null)
                return File(picture.Image, picture.ContentType);

            return File("~/Content/images/Tour/camera-photo-min.png", "image/jpeg");
        }

        public ActionResult GetImage(int id)
        {
            Photo picture = manager.GetPhotoByID(id);


            if (picture != null)
                return File(picture.Image, picture.ContentType);

            return File("~/Content/images/Tour/camera-photo-min.png", "image/jpeg");
        }
    }
}

TravelBug/Views/Excursion/GetAllExcursions.cshtml
@model TravelBug.Models.TravelBugModel.Excursion
@{
    ViewBag.Title = "GetAllExcursions";
}

<h2>GetAllExcursions</h2>

<div>
    @{

        var Excursions = (List<TravelBug.Models.TravelBugModel.Excursion>)ViewBag.Excursions;

        <table>
            <tr>
                <th>@Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })</th>
                <th>@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })</th>
                <th>@Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })</th>
                <th>@Html.LabelFor(model => model.Language.FirstOrDefault().Name_Language, htmlAttributes: new { @class = "control-label col-md-2" })</th>
                <th>@Html.LabelFor(model => model.Photo.FirstOrDefault().Image, htmlAttributes: new { @class = "control-label col-md-2" })</th>
            </tr>
            @for (int i = 0; i < Excursions.Count; i++)
            {

                <tr>
                    <td>@Html.ActionLink(Excursions[i].Title, "Index", "EditExcursion", new { excursionID = @Excursions[i].Id }, new { @class = "button alt small" })</td>
                    <td>@Excursions[i].Description</td>
                    <td>@Excursions[i].Time</td>
                    <td>
                        @if (@Excursions[i].Language.Count() != 0)
                        {
                            @Excursions[i].Language.ElementAt(0).Name_Language;
                        }
                    </td>
                    <td>
                        @if (Excursions[i].Photo.Count() != 0)
                        {
                            <img id="img" src="@Url.Action("GetUrlFromPictureOfExcursion", "ShowImage",
      new
      {
          excursionID = Excursions[i].Id
      })"
                                 alt="" />
                        }
                        else
                        {
                            <img id="img" src="~/images/Tour/camera-photo-min.png" alt="" style=" width: 10%; margin: 0 auto 0 auto;" />
                        }
                    </td>
                </tr>

            }
        </table>
    }
</div>

TravelBug/Views/Excursion/View.cshtml
@{
    ViewBag.Title = "TraveBug - Tour";
    this.Layout = "~/Views/Shared/_LayoutMin.cshtml";

}
<style>
    .s48 {
        width: 68px;
        height: 68px;
    }

    .span4 {
        margin-left: 18%;
    }

    .imgMax {
        width: 630px;
        height: 425px;
    }

    .image_background {
        background-image: url(../../Content/Style/images/dark_tint.png), url(../../Content/Style/images/Moscow_min.jpg);
        background-position: center center;
        background-size: cover;
    }


    /*#region Loader */
    .load_circular {
        height: 135px;
    }

    /*#endregion */

    /*#region text description */

    section.special.image_background {
        text-align: inherit;
    }

    /*#endregion */

    /*#region Обратная связь */

    div.row.uniform  input {
        border: 1px solid black;
    }
      div.row.uniform  textarea{
        border: 1px solid black;
    }


    /*#endregion */

    /*Костыль, почему в футоре появляется див пустой*/
    #skel-layers-hiddenWrapper {
        height: 0% !important;
    }
</style>


<script>
    var tourID = @ViewBag.ExcursionID;
</script>

<section id="main" class="wrapper style1 special image_background">
    @*<div ng-include src="'../../TravelBug.UI/Partials_UI/TourPartialView.html'"></div>*@

    <div class="container" ng-controller="excursionCtrl as exCtrl">

        <md-content layout-padding class="load_circular" ng-if="!isReady">
            @*ng-if="!isReady"*@
            <div layout="row" layout-sm="column" layout-align="space-around">
                <md-progress-circular md-diameter="96"></md-progress-circular>
            </div>
        </md-content>

        <section class="box style1" ng-cloak ng-if="isReady">
            <header class="major">
                <h3>{{ tour.Title }} </h3>
            </header>
            <div class="row">
                <div class="span4 text-center" ng-if="tour.Time">
                    <md-icon class="s48" md-svg-icon="../../Content/images/UI/time.svg"></md-icon>
                    <p>{{ tour.Time.Option }}</p>
                </div>
                <div class="span4 text-center" ng-if="tour.Cost">

                    <md-icon class="s48" md-svg-icon="../../Content/images/UI/money_on.svg"></md-icon>
                    <p>{{ tour.Cost.Money }}</p>
                </div>
                <div class="span4" ng-if="!tour.Cost">
                    <md-icon class="s48" md-svg-icon="../../Content/images/UI/money_off.svg"></md-icon>
                </div>
                <div class="span4 ">
                    <md-icon class="s48" md-svg-icon="../../Content/images/UI/talk.svg"></md-icon>
                    <div>
                        <div ng-repeat="lang in tour.Language" style=" margin-bottom: -15px;">
                            <p>{{ lang.Name_Language }}</p>
                        </div>
                    </div>
                </div>
            </div>
            <p>
                <div class="row">
                    @*<textarea ng-model="tour.Description" readonly="readonly"></textarea>*@
                    <div class="col-md-5">
                        <xmp style="white-space: pre-wrap;">{{ tour.Description }}</xmp>
                    </div>
                    <div class="col-md-6">
                        <div>
                            <div ng-repeat="image in tour.Photo" style="{{ image.Delete ? '' : 'display: none;'}}" class="md-shadow" ng-click="showNextImage();">
                                <img id="{{ image.ID }}" ng-src="data:{{image.ContentType}};base64,{{image.Image}}"
                                     alt="{{ image.FileName }}" class="img-fluid imgMax" />
                            </div>
                        </div>
                    </div>

                </div>
            </p>

            <section>
                <div class="table-wrapper 4u 12u$(medium)">
                    <table class="alt">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Description</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Tour duration:</td>
                                <td>Bright and energetic local, young, enthusiastic, and fun! Your guide is your local friend.</td>
                            </tr>
                            <tr>
                                <td>Sights to see:</td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>Activity Level:</td>
                                <td>high</td>
                            </tr>
                            <tr>
                                <td>Maximum travelers:</td>
                                <td>4</td>
                            </tr>
                            <tr>
                                <td>Pick up &amp; Drop off:</td>
                                <td>Lobby of your hotel or any place you wish</td>
                            </tr>
                            <tr>
                                <td>Start time:</td>
                                <td>9am - 12pm</td>
                            </tr>
                            <tr>
                                <td>Extra hours:</td>
                                <td>If you are having a good time and want your St Petersburg tour last a little bit longer, you are welcome to do that. Please note: You will be charged 20 USD per an extra hour.</td>
                            </tr>
                            <tr>
                                <td>Terms of cancellation</td>
                                <td>Cancel up to 1 day in advance for a full refund</td>
                            </tr>
                            <tr>
                                <td>Tipping suggestions:</td>
                                <td>If you feel like you had a good experience, your guide would appreciate a tip. It&#39;s not mandatory. It&#39;s your decision whether you want to give your guide a tip.</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </section>

            @*class style3 делает синий бэкграунд*@
            <section id="three" class="wrapper  special">
                @Html.Partial("~/Views/Partials/ContactFormPartial.cshtml")
            </section>
        </section>
     
    </div>

</section>



@*<section id="three" class="wrapper style3 special">
        @Html.Partial("~/Views/Partials/ContactFormPartial.cshtml")
    </section>*@

<script src="~/TravelBug.UI/Services/TourService.js"></script>
<script src="~/TravelBug.UI/Controllers/ExcursionController.js"></script>