TravelBug/Controllers/Elements/SliderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TravelBug.Controllers.Elements
{
    public class SliderController : BaseController
    {

        public ActionResult SliderPartial(int excursionID)
        {
            ViewData.Model = manager.GetExcursionByID(excursionID).Photo;
            return PartialView("SliderPartial");
        }
    }
}

TravelBug/Controllers/Pages/ExcursionController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelBug.Models.TravelBugModel;

namespace TravelBug.Controllers.Pages
{
    public class ExcursionController : BaseController
    {
        [HttpGet]
        public ActionResult View(int id)
        {
            ViewBag.ExcursionID = id;
            return View();
        }

        [HttpGet]
        public JsonResult GetTourByID(int id)
        {
            var excursion = manager.GetExcursionByID(id);

            Time time = excursion.TimeID != null ? manager.GetTimeByID(excursion.TimeID ?? 0) : null;

            var exc = new
            {
                Id = excursion.Id,
                Title = excursion.Title,
                Description = excursion.Description,
                Time = time,
                Language = excursion.Language.Where(x => x.ID != 0)
                .Select(x =>
                new Language
                {
                    ID = x.ID,
                    Name_Language = x.Name_Language,
                    ExcursionID = x.ExcursionID
                }).ToArray(),
                Photo = excursion.Photo.Where(x => x.Delete != true).Select(x =>
               new Photo
               {
                   ID = x.ID,
                   ExcursionID = x.ExcursionID,
                   FileName = x.FileName,
                   ContentType = x.ContentType,
                   ToMine = x.ToMine,
                   Image = x.Image,
                   Delete = false // Тут delete играет роль "отображение на стороне клиента эту картинку или нет "
               }).ToArray(),
                Cost = new Cost { Money = excursion.Cost.FirstOrDefault().Money }
            };

            if (exc != null && exc.Photo != null) // && exc.Photo.Count != 0)
            {
                var tmpPhoto = exc.Photo.FirstOrDefault();
                if (tmpPhoto != null)
                {
                    tmpPhoto.Delete = true;
                }
            }


            JsonSerializerSettings settings =
              new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };

            var tmp = JsonConvert.SerializeObject(exc, settings);

            return Json(tmp, JsonRequestBehavior.AllowGet);
        }
    }
}

TravelBug/Controllers/Pages/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using TravelBug.Models.TravelBugModel;

namespace TravelBug.Controllers.Pages
{
    public class HomeController : BaseController
    {
        public ActionResult Home()
        {
            ViewBag.Excursions = manager.GetExcursion().ToList();

            return View();
        }


        #region Tour collection

        

        [HttpGet]
        public JsonResult GetTours()
        {
            //var data = manager.GetExcursionByID();

            //var result = (from m in data
            //              where m.Id != 0
            //              select new
            //              {
            //                  id = m.Id,
            //                  Title = m.Title,

            //                  Time = m.TimeID
            //              });

            //return Json(result.ToArray(), JsonRequestBehavior.AllowGet);
            var excursions = manager.GetExcursions();

            // ??
            //if (excursion.Cost != null && excursion.Cost.Count() == 1)
            //{
            //    excursion.Cost.ElementAt(0).Excursion = null;
            //}

            List<Excursion> ex_s = new List<Excursion>();

            foreach (Excursion excursion in excursions)
            {
                Excursion exc = new Excursion
                {
                    Id = excursion.Id,
                    Title = excursion.Title,
                    Description = excursion.Description,
                    TimeID = excursion.TimeID,
                    //      Language = excursion.Language.Where(x => x.ID != 0)
                    //.Select(x =>
                    //new Language
                    //{
                    //    ID = x.ID,
                    //    Name_Language = x.Name_Language,
                    //    ExcursionID = x.ExcursionID
                    //}).ToArray(),
                    Photo = excursion.Photo.Where(x => x.Delete != true && x.ToMine).Select(x =>
                   new Photo
                   {
                       ID = x.ID,
                       ExcursionID = x.ExcursionID,
                       FileName = x.FileName,
                       ContentType = x.ContentType,
                       ToMine = x.ToMine,
                       Image = x.Image,
                       Delete = x.Delete
                   }).ToArray(),
                    Cost = excursion.Cost
                };

                ex_s.Add(exc);
            }


            //Что бы не было цикличной сериализации
            JsonSerializerSettings settings =
                new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };

            var tmp = JsonConvert.SerializeObject(ex_s, settings);
            return Json(tmp, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetPhotoByTourID(int id)
        {
            var data = manager.GetMainPhotoByExcursionID(id);

            //Что бы не было цикличной сериализации
            JsonSerializerSettings settings =
                new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };


            var tmp = JsonConvert.SerializeObject(data, settings);

            return Json(tmp, JsonRequestBehavior.AllowGet);
        }

        #endregion

    }
}

TravelBug/Views/Home/Home.cshtml
@{
    ViewBag.Title = "Index";

}

<script src="~/TravelBug.UI/Services/TourService.js"></script>
<script src="~/TravelBug.UI/Controllers/ExcursionsController.js"></script>


@*@Html.Action("View", "Slider")*@
@*<section id="two" class="wrapper style2 special slider">
        @Html.Partial("~/Views/Partials/SliderPartialView.cshtml")
    </section>*@

<section id="one" class="wrapper style1 special" ng-controller="excursionsCtrl as exsCtrl">
    <div class="container">
        <header class="major">
            <h2>Other excursions:</h2>
            @*<p>Lorem ipsum dolor sit amet, delectus consequatur, similique quia!</p>*@
        </header>
        <style>
            section img {
                max-width: 100%;
                max-height: 100%;
            }
        </style>
        <div class="row 100%">
            <div ng-repeat="tour in tours" class="4u 12u$(medium)" id="{{ tour.Id }}">
                <section class="box">
                    <a href="../Excursion/View/{{ tour.Id }}" id="link_{{ tour.Id }}">
                        <img ng-repeat="image in tour.Photo" class="imgTour"
                             id="{{ image.ID }}" ng-src="data:{{image.ContentType}};base64,{{image.Image}}"
                             alt="{{ image.FileName }}" />
                        <img ng-show="tour.Photo.length == 0" src="../Content/images/UI/no_image.svg" />
                    </a>
                    <a href="../Excursion/View/{{ tour.Id }}">
                        <h3>{{ tour.Title }}</h3>
                    </a>
                    <md-card-actions layout="row" layout-align="center">
                        <md-button class="md-icon-button" aria-label="Favorite">
                            <md-icon md-svg-icon="../Content/images/UI/favorite.svg"></md-icon>
                        </md-button>
                        <md-button class="md-icon-button" aria-label="Settings">
                            <md-icon md-svg-icon="../Content/images/UI/filter_list.svg"></md-icon>
                        </md-button>
                        <md-button class="md-icon-button" aria-label="Share">
                            <md-icon md-svg-icon="../Content/images/UI/open_new.svg"></md-icon>
                        </md-button>
                    </md-card-actions>
                </section>
            </div>
        </div>
        <style>
            .imgTour {
                transition: all .2s ease-in-out;
                opacity: 0.8;
            }

                .imgTour:hover {
                    transform: scale(1.1);
                    opacity: 1;
                }
        </style>







        @* <div ng-include src="'../TravelBug.UI/Partials_UI/ToursPartialView.html'"></div>*@
    </div>
</section>
@*@Html.Action("AdminPage", "Excursion")*@
@*@{
        List<TravelBug.Models.TravelBugModel.Excursion> excursions = (List<TravelBug.Models.TravelBugModel.Excursion>)ViewBag.Excursions;
        @Html.Partial("~/Views/Partials/ExursionsPartialView.cshtml", excursions)
    }*@


<section id="three" class="wrapper style3 special">
    @Html.Partial("~/Views/Partials/ContactFormPartial.cshtml")
</section>

TravelBug/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
   
}

    @*@Html.Action("View", "Slider")*@
    <section id="two" class="wrapper style2 special slider">
        @Html.Partial("~/Views/Partials/SliderParialView.cshtml")
    </section>
<section id="one" class="wrapper style1 special">
    @*@Html.Action("GetAllExcursions", "Excursion")*@
    @{
        List<TravelBug.Models.TravelBugModel.Excursion> excursions = (List<TravelBug.Models.TravelBugModel.Excursion>)ViewBag.Excursions;
        @Html.Partial("~/Views/Partials/ExursionsPartialView.cshtml", excursions)
    }
</section>
<section id="three" class="wrapper style3 special">
    @Html.Partial("~/Views/Partials/ContactFormPartial.cshtml")
</section>

TravelBug/Views/Home/MainView.cshtml
@{
    ViewBag.Title = "Index";

}

@*@Html.Action("View", "Slider")*@
<section id="two" class="wrapper style2 special slider">
    @Html.Partial("~/Views/Partials/SliderPartialView.cshtml")
</section>
<section id="one" class="wrapper style1 special">
    @*@Html.Action("AdminPage", "Excursion")*@
    @{
        List<TravelBug.Models.TravelBugModel.Excursion> excursions = (List<TravelBug.Models.TravelBugModel.Excursion>)ViewBag.Excursions;
        @Html.Partial("~/Views/Partials/ExursionsPartialView.cshtml", excursions)
    }
</section>
<section id="three" class="wrapper style3 special">
    @Html.Partial("~/Views/Partials/ContactFormPartial.cshtml")
</section>

TravelBug/Views/Home/Old_Home.cshtml
@{
    ViewBag.Title = "Index";

}

@*@Html.Action("View", "Slider")*@
<section id="two" class="wrapper style2 special slider">
    @Html.Partial("~/Views/Partials/SliderPartialView.cshtml")
</section>
<section id="one" class="wrapper style1 special">
    @*@Html.Action("AdminPage", "Excursion")*@
    @{
        List<TravelBug.Models.TravelBugModel.Excursion> excursions = (List<TravelBug.Models.TravelBugModel.Excursion>)ViewBag.Excursions;
        @Html.Partial("~/Views/Partials/ExursionsPartialView.cshtml", excursions)
    }
</section>
<section id="three" class="wrapper style3 special">
    @Html.Partial("~/Views/Partials/ContactFormPartial.cshtml")
</section>